Create Database Library;

use Library;


CREATE TABLE EMPLOYEE(
Emp_ID    CHAR(11)      NOT NULL,
Emp_Type     VARCHAR(30)   NOT NULL,
EMP_FN        VARCHAR(30)   NOT NULL,
EMP_LN        VARCHAR(30)   NOT NULL,
Emp_PhoneNo   INTEGER  NOT NUll,
Emp_Email      VARCHAR(30)   NOT NULL,
CONSTRAINT EmpPK PRIMARY KEY(EMP_ID,Emp_Type));


CREATE TABLE EVENT(
Event_ID     CHAR(4)       NOT NULL,
Event_Name    VARCHAR(30)   NOT NULL,
Event_Venue   VARCHAR(30)   NOT NULL,
Event_Desc    VARCHAR(30)   NOT NULL,
Emp_ID    CHAR(11)      NOT NULL, 
Emp_Type     VARCHAR(30)   NOT NULL,
CONSTRAINT EventPK PRIMARY KEY(Event_ID),
CONSTRAINT EmpID_FK FOREIGN KEY(EMP_ID,Emp_Type) REFERENCES EMPLOYEE(EMP_ID,Emp_Type));


CREATE TABLE LIBRARIAN(
Emp_ID    CHAR(11)      NOT NULL,
Emp_Type     VARCHAR(30)   NOT NULL,
CONSTRAINT EmpTypePK PRIMARY KEY(Emp_Type),
CONSTRAINT EmpFK FOREIGN KEY(EMP_ID,Emp_Type) REFERENCES EMPLOYEE(EMP_ID,Emp_Type));


CREATE TABLE VOLUNTEER(
Emp_ID    CHAR(11)      NOT NULL,
Emp_Type     VARCHAR(30)   NOT NULL,
Event_ID     CHAR(4)       NOT NULL,
Event_Name    VARCHAR(30)   NOT NULL,
CONSTRAINT EmpTPPK PRIMARY KEY(Emp_Type),
CONSTRAINT EmpVolFK FOREIGN KEY(EMP_ID,Emp_Type) REFERENCES EMPLOYEE(EMP_ID,Emp_Type),
CONSTRAINT EventFK FOREIGN KEY(Event_ID) REFERENCES EVENT(Event_ID));




CREATE TABLE STUDENT(
Stud_ID      CHAR(4)      NOT NULL,
Stud_FN        VARCHAR(30)   NOT NULL,
Stud_LN        VARCHAR(30)   NOT NULL,
Stud_Email      VARCHAR(30)   NOT NULL,
Stud_Book_Limit  INTEGER      NOT Null,
CONSTRAINT Stud_ID_PK PRIMARY KEY(Stud_ID));


CREATE TABLE REGISTRATION(
Event_ID     CHAR(4)       NOT NULL,
Stud_ID      CHAR(4)       NOT NULL,
CONSTRAINT EmpRegisterPK PRIMARY KEY(Event_ID,Stud_ID),
CONSTRAINT Stud_ID_FK FOREIGN KEY(Stud_ID) REFERENCES STUDENT,
CONSTRAINT Event_ID_FK FOREIGN KEY(Event_ID) REFERENCES EVENT);


CREATE TABLE BOOK(
Book_ID      VARCHAR(10)      NOT NULL,
Book_Name      VARCHAR(30)   NOT NULL,
Book_Genre     VARCHAR(30)   NOT NULL,
Book_Author_FN  VARCHAR(30)      NOT Null,
Book_Author_LN  VARCHAR(30)      NOT Null,
CONSTRAINT Book_ID_PK PRIMARY KEY(Book_ID));

CREATE TABLE FINE(
Fine_ID      VARCHAR(10)      NOT NULL,
Fine_Due_Date  DATETIME       NOT NULL,
Fine_Amount     Decimal(5,2)   NOT NULL,
CONSTRAINT Fine_ID_PK PRIMARY KEY(Fine_ID));

